# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Chromeless
description: Chromeless is a free tool for Mac, PC & Linux computers that allows you to create Chromium-based or WebKit-based apps from any websites.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chromeless.app" # the base hostname & protocol for your site, e.g. http://example.com

chromeless_version: 1.6.1
webkit_wrapper_version: 2.0.2
webkit_wrapper_version_prerelease: 2.0.2

permalink: pretty

pagination:
  enabled: true

markdown: kramdown
plugins:
  - jekyll-sitemap

exclude:
  - yarn.lock
  - package.json
  - scripts
